const STORAGE_KEY="seibi_records_good_look_seeded_v1";let state=JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(window.SEED_STATE);const $=id=>document.getElementById(id);
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function today(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function addMonths(s,m){if(!m)return"";const d=new Date(s+"T00:00:00");d.setMonth(d.getMonth()+Number(m));d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function yen(n){return Number(n||0).toLocaleString("ja-JP")} function km(n){return Number(n||0).toLocaleString("ja-JP")}
function esc(t){return String(t??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function selectedCycle(){return state.cycles.find(c=>c.name===$("work").value)||{km:0,month:0}}
function calcNext(){const b=Number($("km").value||0),d=$("date").value||today(),ck=Number($("cycleKm").value||0),cm=Number($("cycleMonth").value||0);return{nextKm:b&&ck?b+ck:0,nextDate:cm?addMonths(d,cm):"",cycleKm:ck,cycleMonth:cm}}
function updateCycleInputs(){const c=selectedCycle();$("cycleKm").value=c.km||"";$("cycleMonth").value=c.month||"";updateNextPreview()}
function updateNextPreview(){const n=calcNext(),p=[];if(n.nextKm)p.push(`${km(n.nextKm)} km`);if(n.nextDate)p.push(n.nextDate);$("nextPreview").textContent=p.length?`次回目安：${p.join(" または ")}`:"この項目は目視・症状判断用です。必要ならサイクルを手入力してください。"}
function renderSelects(){$("car").innerHTML=state.cars.map(c=>`<option>${esc(c)}</option>`).join("");$("work").innerHTML=state.cycles.map(c=>`<option>${esc(c.name)}</option>`).join("")}
function renderCycles(){$("cycleList").innerHTML=state.cycles.map(c=>`<div class="cycle"><strong>${esc(c.name)}</strong><div>距離：${c.km?km(c.km)+" km":"指定なし"}<br>期間：${c.month?c.month+"ヶ月":"指定なし"}</div></div>`).join("")}
function latestByCarWork(){const latest={};[...state.records].sort((a,b)=>new Date(b.date)-new Date(a.date)||Number(b.km||0)-Number(a.km||0)).forEach(r=>{const k=r.car+"::"+r.work;if(!latest[k])latest[k]=r});return Object.values(latest)}
function alertInfo(r){const now=Number($("nowKm").value||state.currentMileage||0),remain=r.nextKm?r.nextKm-now:null,dateDue=r.nextDate&&r.nextDate<=today();if((remain!==null&&remain<=0)||dateDue)return{label:"交換時期",cls:"danger",rank:0,remain};if(remain!==null&&remain<=1000)return{label:"そろそろ",cls:"warn",rank:1,remain};return{label:"余裕あり",cls:"ok",rank:2,remain}}
function renderAlerts(){const items=latestByCarWork().filter(r=>r.nextKm||r.nextDate).map(r=>({r,info:alertInfo(r)})).sort((a,b)=>a.info.rank-b.info.rank||(a.info.remain??9999999)-(b.info.remain??9999999));$("dueCount").textContent=items.filter(x=>x.info.rank<=1).length;$("currentKm").textContent=km($("nowKm").value||state.currentMileage||0);$("alerts").innerHTML=items.length?items.map(({r,info})=>`<div class="alert"><div class="record-title"><span class="badge ${info.cls}">${info.label}</span>${esc(r.car)} / ${esc(r.work)}</div><div class="record-meta">前回：${esc(r.date)} / ${km(r.km)} km<br>次回：${r.nextKm?km(r.nextKm)+" km":""}${r.nextKm&&r.nextDate?" または ":""}${esc(r.nextDate||"")}<br>${info.remain!==null?"残り：約"+km(info.remain)+" km":""}</div></div>`).join(""):'<div class="empty">交換目安のある記録がありません</div>'}
function addRecord(){const n=calcNext();if(!$("date").value||!$("km").value||!$("work").value){alert("日付・走行距離・整備項目を入力してください。");return}state.records.push({id:Date.now(),car:$("car").value,date:$("date").value,km:Number($("km").value),work:$("work").value,cost:Number($("cost").value||0),memo:$("memo").value.trim(),cycleKm:n.cycleKm,cycleMonth:n.cycleMonth,nextKm:n.nextKm,nextDate:n.nextDate,seeded:false});state.currentMileage=Math.max(Number(state.currentMileage||0),Number($("km").value));$("nowKm").value=state.currentMileage;save();render();$("km").value="";$("cost").value="";$("memo").value="";$("date").value=today();updateNextPreview()}
function deleteRecord(id){if(!confirm("この記録を削除しますか？"))return;state.records=state.records.filter(r=>String(r.id)!==String(id));save();render()}
function renderRecords(){const q=$("search").value.trim().toLowerCase(),sorted=[...state.records].filter(r=>JSON.stringify(r).toLowerCase().includes(q)).sort((a,b)=>new Date(b.date)-new Date(a.date)||Number(b.km||0)-Number(a.km||0));$("count").textContent=state.records.length;$("records").innerHTML=sorted.length?sorted.map(r=>`<div class="record"><div class="record-title"><span class="badge ${r.seeded?"seed":""}">${r.seeded?"初期":"追加"}</span>${esc(r.work)}</div><div class="record-meta">車両：${esc(r.car)}<br>日付：${esc(r.date)}<br>距離：${km(r.km)} km<br>費用：${yen(r.cost)} 円<br>${r.nextKm||r.nextDate?`次回：${r.nextKm?km(r.nextKm)+" km":""}${r.nextKm&&r.nextDate?" または ":""}${esc(r.nextDate||"")}<br>`:""}${r.memo?"メモ："+esc(r.memo).replace(/\n/g,"<br>"):""}</div><button class="delete-btn" onclick="deleteRecord('${r.id}')">削除</button></div>`).join(""):'<div class="empty">記録がありません</div>'}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`seibi-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
function resetSeed(){if(!confirm("追加・変更した内容を消して、初期履歴に戻しますか？"))return;state=structuredClone(window.SEED_STATE);save();init()}
$("search").addEventListener("input",renderRecords);$("nowKm").addEventListener("input",()=>{state.currentMileage=Number($("nowKm").value||0);save();renderAlerts()});$("work").addEventListener("change",updateCycleInputs);["km","date","cycleKm","cycleMonth"].forEach(id=>{$(id).addEventListener("input",updateNextPreview);$(id).addEventListener("change",updateNextPreview)});
$("importFile").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;const data=JSON.parse(await f.text());if(!data.records){alert("読み込めない形式です。");return}state=data;if(!state.cars)state.cars=window.SEED_STATE.cars;if(!state.cycles)state.cycles=window.SEED_STATE.cycles;save();init()});
function render(){renderAlerts();renderRecords()} function init(){renderSelects();renderCycles();$("nowKm").value=state.currentMileage||"";$("date").value=today();updateCycleInputs();render()} if("serviceWorker"in navigator){navigator.serviceWorker.register("service-worker.js").catch(()=>{})} init();