window.SEED_STATE = {
  "cars": [
    {
      "name": "GK5 フィット",
      "currentMileage": 348102,
      "mainPhoto": "",
      "model": "DBA-GK5",
      "number": "",
      "purchaseDate": "",
      "memo": ""
    },
    {
      "name": "FR5 ジェイド",
      "currentMileage": 0,
      "mainPhoto": "",
      "model": "DBA-FR5",
      "number": "",
      "purchaseDate": "",
      "memo": ""
    }
  ],
  "selectedCar": "GK5 フィット",
  "cycles": [
    {
      "category": "交換",
      "name": "エンジンオイル",
      "km": 5000,
      "month": 6
    },
    {
      "category": "交換",
      "name": "オイルフィルター",
      "km": 10000,
      "month": 12
    },
    {
      "category": "交換",
      "name": "ミッションオイル",
      "km": 30000,
      "month": 24
    },
    {
      "category": "交換",
      "name": "ブレーキフルード",
      "km": 0,
      "month": 24
    },
    {
      "category": "交換",
      "name": "クラッチフルード",
      "km": 0,
      "month": 24
    },
    {
      "category": "交換",
      "name": "冷却水 LLC",
      "km": 0,
      "month": 48
    },
    {
      "category": "交換",
      "name": "エアクリーナー",
      "km": 30000,
      "month": 24
    },
    {
      "category": "交換",
      "name": "エアコンフィルター",
      "km": 10000,
      "month": 12
    },
    {
      "category": "交換",
      "name": "スパークプラグ",
      "km": 100000,
      "month": 0
    },
    {
      "category": "交換",
      "name": "タイヤローテーション",
      "km": 5000,
      "month": 6
    },
    {
      "category": "交換",
      "name": "タイヤ交換",
      "km": 0,
      "month": 60
    },
    {
      "category": "交換",
      "name": "ブレーキパッド",
      "km": 0,
      "month": 0
    },
    {
      "category": "交換",
      "name": "ブレーキローター",
      "km": 0,
      "month": 0
    },
    {
      "category": "交換",
      "name": "バッテリー",
      "km": 0,
      "month": 36
    },
    {
      "category": "交換",
      "name": "クラッチ",
      "km": 0,
      "month": 0
    },
    {
      "category": "調整",
      "name": "アライメント",
      "km": 0,
      "month": 12
    },
    {
      "category": "調整",
      "name": "サイドブレーキ",
      "km": 0,
      "month": 0
    },
    {
      "category": "調整",
      "name": "光軸",
      "km": 0,
      "month": 0
    },
    {
      "category": "調整",
      "name": "クラッチペダル",
      "km": 0,
      "month": 0
    },
    {
      "category": "清掃",
      "name": "スロットルボデー",
      "km": 0,
      "month": 12
    },
    {
      "category": "清掃",
      "name": "エアフロ",
      "km": 0,
      "month": 12
    },
    {
      "category": "清掃",
      "name": "エアコンフィルター周り",
      "km": 0,
      "month": 12
    },
    {
      "category": "清掃",
      "name": "ブレーキ周り",
      "km": 0,
      "month": 0
    },
    {
      "category": "交換",
      "name": "ワイパーゴム",
      "km": 0,
      "month": 12
    },
    {
      "category": "交換",
      "name": "車検",
      "km": 0,
      "month": 24
    },
    {
      "category": "交換",
      "name": "その他",
      "km": 0,
      "month": 0
    },
    {
      "category": "調整",
      "name": "その他",
      "km": 0,
      "month": 0
    },
    {
      "category": "清掃",
      "name": "その他",
      "km": 0,
      "month": 0
    }
  ],
  "records": [
    {
      "id": "seed-1",
      "car": "GK5 フィット",
      "date": "2022-07-28",
      "km": 244644,
      "category": "交換",
      "work": "クラッチ",
      "cost": 0,
      "memo": "クラッチ交換",
      "cycleKm": 0,
      "cycleMonth": 0,
      "nextKm": 0,
      "nextDate": "",
      "seeded": true
    },
    {
      "id": "seed-2",
      "car": "GK5 フィット",
      "date": "2022-07-28",
      "km": 244644,
      "category": "交換",
      "work": "ミッションオイル",
      "cost": 0,
      "memo": "ミッションオイル交換",
      "cycleKm": 30000,
      "cycleMonth": 24,
      "nextKm": 274644,
      "nextDate": "2024-07-28",
      "seeded": true
    },
    {
      "id": "seed-3",
      "car": "GK5 フィット",
      "date": "2022-07-29",
      "km": 244940,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 249940,
      "nextDate": "2023-01-29",
      "seeded": true
    },
    {
      "id": "seed-4",
      "car": "GK5 フィット",
      "date": "2022-07-29",
      "km": 244940,
      "category": "交換",
      "work": "オイルフィルター",
      "cost": 0,
      "memo": "オイルフィルター交換",
      "cycleKm": 10000,
      "cycleMonth": 12,
      "nextKm": 254940,
      "nextDate": "2023-07-29",
      "seeded": true
    },
    {
      "id": "seed-5",
      "car": "GK5 フィット",
      "date": "2022-10-07",
      "km": 257000,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 262000,
      "nextDate": "2023-04-07",
      "seeded": true
    },
    {
      "id": "seed-6",
      "car": "GK5 フィット",
      "date": "2022-10-07",
      "km": 257000,
      "category": "交換",
      "work": "オイルフィルター",
      "cost": 0,
      "memo": "オイルフィルター交換",
      "cycleKm": 10000,
      "cycleMonth": 12,
      "nextKm": 267000,
      "nextDate": "2023-10-07",
      "seeded": true
    },
    {
      "id": "seed-7",
      "car": "GK5 フィット",
      "date": "2022-11-30",
      "km": 262035,
      "category": "交換",
      "work": "ブレーキフルード",
      "cost": 0,
      "memo": "ブレーキフルード交換 / タイロッドエンドブーツ・ドライブシャフトブーツ",
      "cycleKm": 0,
      "cycleMonth": 24,
      "nextKm": 0,
      "nextDate": "2024-11-30",
      "seeded": true
    },
    {
      "id": "seed-8",
      "car": "GK5 フィット",
      "date": "2022-11-30",
      "km": 262035,
      "category": "交換",
      "work": "クラッチフルード",
      "cost": 0,
      "memo": "クラッチフルード交換 / タイロッドエンドブーツ・ドライブシャフトブーツ",
      "cycleKm": 0,
      "cycleMonth": 24,
      "nextKm": 0,
      "nextDate": "2024-11-30",
      "seeded": true
    },
    {
      "id": "seed-9",
      "car": "GK5 フィット",
      "date": "2022-11-30",
      "km": 262035,
      "category": "交換",
      "work": "ミッションオイル",
      "cost": 0,
      "memo": "ミッションオイル交換 / タイロッドエンドブーツ・ドライブシャフトブーツ",
      "cycleKm": 30000,
      "cycleMonth": 24,
      "nextKm": 292035,
      "nextDate": "2024-11-30",
      "seeded": true
    },
    {
      "id": "seed-10",
      "car": "GK5 フィット",
      "date": "2023-02-01",
      "km": 270634,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 275634,
      "nextDate": "2023-08-01",
      "seeded": true
    },
    {
      "id": "seed-11",
      "car": "GK5 フィット",
      "date": "2023-02-01",
      "km": 270634,
      "category": "交換",
      "work": "オイルフィルター",
      "cost": 0,
      "memo": "オイルフィルター交換",
      "cycleKm": 10000,
      "cycleMonth": 12,
      "nextKm": 280634,
      "nextDate": "2024-02-01",
      "seeded": true
    },
    {
      "id": "seed-12",
      "car": "GK5 フィット",
      "date": "2023-04-04",
      "km": 280134,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 285134,
      "nextDate": "2023-10-04",
      "seeded": true
    },
    {
      "id": "seed-13",
      "car": "GK5 フィット",
      "date": "2023-04-04",
      "km": 280134,
      "category": "交換",
      "work": "オイルフィルター",
      "cost": 0,
      "memo": "オイルフィルター交換",
      "cycleKm": 10000,
      "cycleMonth": 12,
      "nextKm": 290134,
      "nextDate": "2024-04-04",
      "seeded": true
    },
    {
      "id": "seed-14",
      "car": "GK5 フィット",
      "date": "2023-07-03",
      "km": 288297,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 293297,
      "nextDate": "2024-01-03",
      "seeded": true
    },
    {
      "id": "seed-15",
      "car": "GK5 フィット",
      "date": "2023-07-03",
      "km": 288297,
      "category": "交換",
      "work": "オイルフィルター",
      "cost": 0,
      "memo": "オイルフィルター交換",
      "cycleKm": 10000,
      "cycleMonth": 12,
      "nextKm": 298297,
      "nextDate": "2024-07-03",
      "seeded": true
    },
    {
      "id": "seed-16",
      "car": "GK5 フィット",
      "date": "2023-11-01",
      "km": 296687,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 301687,
      "nextDate": "2024-05-01",
      "seeded": true
    },
    {
      "id": "seed-17",
      "car": "GK5 フィット",
      "date": "2023-11-01",
      "km": 296687,
      "category": "交換",
      "work": "オイルフィルター",
      "cost": 0,
      "memo": "オイルフィルター交換",
      "cycleKm": 10000,
      "cycleMonth": 12,
      "nextKm": 306687,
      "nextDate": "2024-11-01",
      "seeded": true
    },
    {
      "id": "seed-18",
      "car": "GK5 フィット",
      "date": "2024-01-16",
      "km": 304080,
      "category": "交換",
      "work": "ブレーキフルード",
      "cost": 0,
      "memo": "ブレーキフルード交換 / リヤディスク・パッド",
      "cycleKm": 0,
      "cycleMonth": 24,
      "nextKm": 0,
      "nextDate": "2026-01-16",
      "seeded": true
    },
    {
      "id": "seed-19",
      "car": "GK5 フィット",
      "date": "2024-01-16",
      "km": 304080,
      "category": "交換",
      "work": "ブレーキパッド",
      "cost": 0,
      "memo": "ブレーキパッド交換 / リヤディスク・パッド",
      "cycleKm": 0,
      "cycleMonth": 0,
      "nextKm": 0,
      "nextDate": "",
      "seeded": true
    },
    {
      "id": "seed-20",
      "car": "GK5 フィット",
      "date": "2024-01-29",
      "km": 305134,
      "category": "交換",
      "work": "ミッションオイル",
      "cost": 0,
      "memo": "ミッションオイル交換 / 左右ドライブシャフト",
      "cycleKm": 30000,
      "cycleMonth": 24,
      "nextKm": 335134,
      "nextDate": "2026-01-29",
      "seeded": true
    },
    {
      "id": "seed-21",
      "car": "GK5 フィット",
      "date": "2024-02-06",
      "km": 305981,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 310981,
      "nextDate": "2024-08-06",
      "seeded": true
    },
    {
      "id": "seed-22",
      "car": "GK5 フィット",
      "date": "2024-02-06",
      "km": 305981,
      "category": "交換",
      "work": "オイルフィルター",
      "cost": 0,
      "memo": "オイルフィルター交換",
      "cycleKm": 10000,
      "cycleMonth": 12,
      "nextKm": 315981,
      "nextDate": "2025-02-06",
      "seeded": true
    },
    {
      "id": "seed-23",
      "car": "GK5 フィット",
      "date": "2024-03-01",
      "km": 308106,
      "category": "交換",
      "work": "バッテリー",
      "cost": 0,
      "memo": "バッテリー交換 / N－N80",
      "cycleKm": 0,
      "cycleMonth": 36,
      "nextKm": 0,
      "nextDate": "2027-03-01",
      "seeded": true
    },
    {
      "id": "seed-24",
      "car": "GK5 フィット",
      "date": "2024-05-02",
      "km": 312785,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 317785,
      "nextDate": "2024-11-02",
      "seeded": true
    },
    {
      "id": "seed-25",
      "car": "GK5 フィット",
      "date": "2024-07-08",
      "km": 317966,
      "category": "交換",
      "work": "タイヤ交換",
      "cost": 0,
      "memo": "タイヤ交換交換 / ADVAN FLEVA 205/50R16",
      "cycleKm": 0,
      "cycleMonth": 60,
      "nextKm": 0,
      "nextDate": "2029-07-08",
      "seeded": true
    },
    {
      "id": "seed-26",
      "car": "GK5 フィット",
      "date": "2024-08-13",
      "km": 320031,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換 / トップコイル",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 325031,
      "nextDate": "2025-02-13",
      "seeded": true
    },
    {
      "id": "seed-27",
      "car": "GK5 フィット",
      "date": "2024-08-13",
      "km": 320031,
      "category": "交換",
      "work": "スパークプラグ",
      "cost": 0,
      "memo": "スパークプラグ交換 / トップコイル",
      "cycleKm": 100000,
      "cycleMonth": 0,
      "nextKm": 420031,
      "nextDate": "",
      "seeded": true
    },
    {
      "id": "seed-28",
      "car": "GK5 フィット",
      "date": "2024-09-30",
      "km": 325366,
      "category": "交換",
      "work": "その他",
      "cost": 0,
      "memo": "その他 / A/Cベルト・アイドラプーリー・オルタネーター・ウォータープーリー・クランクプーリー",
      "cycleKm": 0,
      "cycleMonth": 0,
      "nextKm": 0,
      "nextDate": "",
      "seeded": true
    },
    {
      "id": "seed-29",
      "car": "GK5 フィット",
      "date": "2024-11-25",
      "km": 329234,
      "category": "調整",
      "work": "アライメント",
      "cost": 0,
      "memo": "アライメント / （記号：A） / 左右スタビリンク・リヤピースマフラー",
      "cycleKm": 0,
      "cycleMonth": 12,
      "nextKm": 0,
      "nextDate": "2025-11-25",
      "seeded": true
    },
    {
      "id": "seed-30",
      "car": "GK5 フィット",
      "date": "2024-12-03",
      "km": 330087,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 335087,
      "nextDate": "2025-06-03",
      "seeded": true
    },
    {
      "id": "seed-31",
      "car": "GK5 フィット",
      "date": "2024-12-03",
      "km": 330087,
      "category": "交換",
      "work": "オイルフィルター",
      "cost": 0,
      "memo": "オイルフィルター交換",
      "cycleKm": 10000,
      "cycleMonth": 12,
      "nextKm": 340087,
      "nextDate": "2025-12-03",
      "seeded": true
    },
    {
      "id": "seed-32",
      "car": "GK5 フィット",
      "date": "2025-01-14",
      "km": 333739,
      "category": "交換",
      "work": "ブレーキパッド",
      "cost": 0,
      "memo": "ブレーキパッド交換 / フロントディスク・パッド",
      "cycleKm": 0,
      "cycleMonth": 0,
      "nextKm": 0,
      "nextDate": "",
      "seeded": true
    },
    {
      "id": "seed-33",
      "car": "GK5 フィット",
      "date": "2025-02-03",
      "km": 334600,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 339600,
      "nextDate": "2025-08-03",
      "seeded": true
    },
    {
      "id": "seed-34",
      "car": "GK5 フィット",
      "date": "2025-02-03",
      "km": 334600,
      "category": "交換",
      "work": "オイルフィルター",
      "cost": 0,
      "memo": "オイルフィルター交換",
      "cycleKm": 10000,
      "cycleMonth": 12,
      "nextKm": 344600,
      "nextDate": "2026-02-03",
      "seeded": true
    },
    {
      "id": "seed-35",
      "car": "GK5 フィット",
      "date": "2025-05-03",
      "km": 341138,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換 / 部分交換",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 346138,
      "nextDate": "2025-11-03",
      "seeded": true
    },
    {
      "id": "seed-36",
      "car": "GK5 フィット",
      "date": "2025-06-24",
      "km": 344458,
      "category": "交換",
      "work": "エアクリーナー",
      "cost": 0,
      "memo": "エアクリーナー交換",
      "cycleKm": 30000,
      "cycleMonth": 24,
      "nextKm": 374458,
      "nextDate": "2027-06-24",
      "seeded": true
    },
    {
      "id": "seed-37",
      "car": "GK5 フィット",
      "date": "2025-06-24",
      "km": 344458,
      "category": "清掃",
      "work": "スロットルボデー",
      "cost": 0,
      "memo": "スロットルボデー / （記号：C）",
      "cycleKm": 0,
      "cycleMonth": 12,
      "nextKm": 0,
      "nextDate": "2026-06-24",
      "seeded": true
    },
    {
      "id": "seed-38",
      "car": "GK5 フィット",
      "date": "2025-07-02",
      "km": 345852,
      "category": "交換",
      "work": "エンジンオイル",
      "cost": 0,
      "memo": "エンジンオイル交換 / シャンプーあり",
      "cycleKm": 5000,
      "cycleMonth": 6,
      "nextKm": 350852,
      "nextDate": "2026-01-02",
      "seeded": true
    },
    {
      "id": "seed-39",
      "car": "GK5 フィット",
      "date": "2025-07-02",
      "km": 345852,
      "category": "交換",
      "work": "オイルフィルター",
      "cost": 0,
      "memo": "オイルフィルター交換 / シャンプーあり",
      "cycleKm": 10000,
      "cycleMonth": 12,
      "nextKm": 355852,
      "nextDate": "2026-07-02",
      "seeded": true
    },
    {
      "id": "seed-40",
      "car": "GK5 フィット",
      "date": "2025-08-26",
      "km": 347267,
      "category": "交換",
      "work": "タイヤ交換",
      "cost": 0,
      "memo": "タイヤ交換交換 / パンク保証にて4本交換",
      "cycleKm": 0,
      "cycleMonth": 60,
      "nextKm": 0,
      "nextDate": "2030-08-26",
      "seeded": true
    },
    {
      "id": "seed-41",
      "car": "GK5 フィット",
      "date": "2025-11-19",
      "km": 348102,
      "category": "交換",
      "work": "その他",
      "cost": 0,
      "memo": "その他 / ラジエーター交換・サーモスタット交換・冷却水交換",
      "cycleKm": 0,
      "cycleMonth": 0,
      "nextKm": 0,
      "nextDate": "",
      "seeded": true
    }
  ],
  "photos": []
};
